addSbtPlugin("org.scalameta"      % "sbt-scalafmt"              % "2.3.1")
addSbtPlugin("com.github.cb372"   % "sbt-explicit-dependencies" % "0.2.12")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"               % "1.0.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"  % "1.0.0")
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"             % "0.9.0")
addSbtPlugin("com.dwijnand"       % "sbt-dynver"                % "4.0.0")
addSbtPlugin("com.jsuereth"       % "sbt-pgp"                   % "1.1.2")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"              % "3.8.1")
