addSbtPlugin("org.scalameta"      % "sbt-scalafmt"              % "2.0.3")
addSbtPlugin("com.github.cb372"   % "sbt-explicit-dependencies" % "0.2.10")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"               % "0.6.28")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"  % "0.6.1")
addSbtPlugin("ch.epfl.scala"      % "sbt-release-early"         % "2.1.1")
